// backend/auth/roles.js
const ROLES = {
  ADMIN: "ADMIN",
  GERENTE_RRHH: "GERENTE_RRHH",
  ASISTENTE_RRHH: "ASISTENTE_RRHH",
  EMPLEADO: "EMPLEADO",
};

// Permisos (acciones) de negocio
const PERMISSIONS = {
  EMPLEADO_READ_ALL: "EMPLEADO_READ_ALL",
  EMPLEADO_CREATE: "EMPLEADO_CREATE",
  EMPLEADO_UPDATE: "EMPLEADO_UPDATE",
  EMPLEADO_DELETE: "EMPLEADO_DELETE",

  NOMINA_GENERAR: "NOMINA_GENERAR",
  NOMINA_VER_DETALLE: "NOMINA_VER_DETALLE",

  REPORTES_VER: "REPORTES_VER",

  // Acceso del empleado a lo suyo
  SELF_VER_RECIBOS: "SELF_VER_RECIBOS",
  SELF_EDIT_PERFIL: "SELF_EDIT_PERFIL",
};

// Mapa de permisos por rol
const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.EMPLEADO_READ_ALL,
    PERMISSIONS.EMPLEADO_CREATE,
    PERMISSIONS.EMPLEADO_UPDATE,
    PERMISSIONS.EMPLEADO_DELETE,
    PERMISSIONS.NOMINA_GENERAR,
    PERMISSIONS.NOMINA_VER_DETALLE,
    PERMISSIONS.REPORTES_VER,
  ],
  [ROLES.GERENTE_RRHH]: [
    PERMISSIONS.EMPLEADO_READ_ALL,
    PERMISSIONS.NOMINA_VER_DETALLE,
    PERMISSIONS.REPORTES_VER,
    // (gerente NO crea ni edita empleados según tu guía, es más “consulta”)
  ],
  [ROLES.ASISTENTE_RRHH]: [
    PERMISSIONS.EMPLEADO_READ_ALL,
    PERMISSIONS.EMPLEADO_CREATE,
    PERMISSIONS.EMPLEADO_UPDATE,
    PERMISSIONS.NOMINA_GENERAR,
    PERMISSIONS.NOMINA_VER_DETALLE,
  ],
  [ROLES.EMPLEADO]: [
    PERMISSIONS.SELF_VER_RECIBOS,
    PERMISSIONS.SELF_EDIT_PERFIL,
  ],
};

module.exports = { ROLES, PERMISSIONS, ROLE_PERMISSIONS };
